<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Image;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManager $em, Mapping\ClassMetadata $metadata = null)
    {
        parent::__construct($em, $metadata == null ? new Mapping\ClassMetadata(User::class) : $metadata);
    }

    public function getUsers(){

        $db = $this->getEntityManager()->getConnection();
        $qb = $db->createQueryBuilder();

        $qb->select('count(user_id) as images_count,user_id,u.username,u.id')->from('users', 'u')
            ->leftJoin('u','images','i','i.user_id = u.id')
            ->groupBy('u.id')
            ->addOrderBy('images_count','DESC');

        return $qb->execute();
    }

    public function getLastFiveUsers(){

        /**
        return $this->db->select('username')
            ->from('Users')
            ->order_by('id', 'DESC')
            ->limit(5)
            ->get()
            ->result_array();
         **/

        $db = $this->getEntityManager()->getConnection();
        $qb = $db->createQueryBuilder();

        $qb->select('username')->from('users')
            ->addOrderBy('id','DESC')
            ->setMaxResults(5);

        return $qb->execute();

    }
}
